CREATE TABLE `studenttable` (
	`ID` SERIAL,
	`NO` VARCHAR(10) NOT NULL COMMENT '学生番号',
	`NAME` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '学生名',
	`ENT_YEAR` INT(10) COMMENT '入学年度',
	`CLASS_NUM` CHAR(3) COMMENT 'クラス番号',
	`IS_ATTEND` BOOLEAN COMMENT '在学中フラグ',
	`SCHOOL_CD` CHAR(3) COMMENT '学校コード',
	PRIMARY KEY (`NO`)
) ENGINE=InnoDB;