CREATE TABLE `studenttable` (
	`ID` SERIAL NOT NULL,
	`NO` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '学生番号',
	`NAME` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '学生名',
	`ENT_YEAR` INT(10) COMMENT '入学年度',
	`CLASS_NUM` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'クラス番号',
	`IS_ATTEND` BOOLEAN COMMENT '在学中フラグ',
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '学校コード',
	PRIMARY KEY (`NO`)
) ENGINE=InnoDB;