CREATE TABLE `subjecttable` (
	`ID` SERIAL,
	`SCHOOL_CD` CHAR(3) NOT NULL COMMENT '学校コード',
	`CD` VARCHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '科目コード',
	`NAME` VARCHAR(20) COMMENT '科目名',
	PRIMARY KEY (`SCHOOL_CD`,`CD`)
) ENGINE=InnoDB;