CREATE TABLE `teachertable` (
	`TID` SERIAL,
	`ID` VARCHAR(10) NOT NULL COMMENT '教員ID',
	`PASSWORD` VARCHAR(128)  COMMENT 'パスワード',
	`NAME` VARCHAR(10)  COMMENT '氏名',
	`SCHOOL_CD` CHAR(3) COMMENT '学校コード',
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB;